// rs-data-grid-angular/projects/rs-grid-angular/src/lib/rsivri-grid/dialogs/edit-row-dialog.component.ts
import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { IColumn } from '../../models/IColumn';

export interface EditRowDialogData {
  row?: any;
  columns?: IColumn[];
}

interface EditField {
  key: string;
}

@Component({
  selector: 'rsivri-edit-row-dialog',
  standalone: true,
  imports: [MatDialogModule, FormsModule, MatButtonModule],
  templateUrl: './edit-row-dialog.component.html',
  styleUrls: ['./edit-row-dialog.component.css']
})
export class EditRowDialogComponent {
  private readonly dialogRef = inject(MatDialogRef<EditRowDialogComponent, any>);
  readonly data = inject<EditRowDialogData>(MAT_DIALOG_DATA);

  editableRow: Record<string, string> = {};
  fields: EditField[] = [];

  constructor() {
    if (this.data.row) {
      for (const [key, value] of Object.entries(this.data.row)) {
        this.fields.push({ key });
        this.editableRow[key] = value === null || value === undefined ? '' : String(value);
      }
    } else {
      for (const column of this.data.columns ?? []) {
        this.fields.push({ key: column.dataField });
        this.editableRow[column.dataField] = '';
      }
    }
  }

  onSave(): void {
    const result: Record<string, any> = { ...this.data.row };
    for (const field of this.fields) {
      result[field.key] = this.editableRow[field.key];
    }
    this.dialogRef.close(result);
  }

  onCancel(): void {
    this.dialogRef.close(undefined);
  }
}

<h2 mat-dialog-title>{{ data.row ? 'Edit row' : 'Add row' }}</h2>
<mat-dialog-content>
  <div class="edit-form">
    @for (field of fields; track field.key) {
      <div class="edit-row">
        <label class="edit-label">{{ field.key }}</label>
        <input type="text" class="edit-input" [(ngModel)]="editableRow[field.key]" />
      </div>
    }
  </div>
</mat-dialog-content>
<mat-dialog-actions align="end">
  <button mat-button type="button" (click)="onCancel()">Cancel</button>
  <button mat-raised-button color="primary" type="button" (click)="onSave()">Save</button>
</mat-dialog-actions>

// rs-data-grid-react/src/components/rsDataGrid/dialogs/EditRowDialog.tsx
import { useEffect, useState } from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material';
import { IColumn } from '../models/rsDataGrid.models';
import './dialogs.scss';

export interface EditRowDialogProps {
  open: boolean;
  row?: any;
  columns?: IColumn[];
  onSave: (result: Record<string, any>) => void;
  onCancel: () => void;
}

interface EditField {
  key: string;
}

export const EditRowDialog = ({ open, row, columns, onSave, onCancel }: EditRowDialogProps) => {
  const [fields, setFields] = useState<EditField[]>([]);
  const [editableRow, setEditableRow] = useState<Record<string, string>>({});

  useEffect(() => {
    if (!open) {
      return;
    }
    const nextFields: EditField[] = [];
    const nextEditable: Record<string, string> = {};
    if (row) {
      for (const [key, value] of Object.entries(row)) {
        nextFields.push({ key });
        nextEditable[key] = value === null || value === undefined ? '' : String(value);
      }
    } else {
      for (const column of columns ?? []) {
        nextFields.push({ key: column.dataField });
        nextEditable[column.dataField] = '';
      }
    }
    setFields(nextFields);
    setEditableRow(nextEditable);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, row, columns]);

  const handleSave = () => {
    const result: Record<string, any> = { ...row };
    for (const field of fields) {
      result[field.key] = editableRow[field.key];
    }
    onSave(result);
  };

  return (
    <Dialog open={open} onClose={onCancel}>
      <DialogTitle>{row ? 'Edit row' : 'Add row'}</DialogTitle>
      <DialogContent>
        <div className="edit-form">
          {fields.map(field => (
            <div className="edit-row" key={field.key}>
              <label className="edit-label">{field.key}</label>
              <input
                type="text"
                className="edit-input"
                value={editableRow[field.key] ?? ''}
                onChange={e => setEditableRow({ ...editableRow, [field.key]: e.target.value })}
              />
            </div>
          ))}
        </div>
      </DialogContent>
      <DialogActions>
        <Button onClick={onCancel}>Cancel</Button>
        <Button variant="contained" color="primary" onClick={handleSave}>
          Save
        </Button>
      </DialogActions>
    </Dialog>
  );
};
