// rs-data-grid-react/src/components/rsDataGrid/rsDataGridPager/rsDataGridPager.tsx
import { useEffect, useRef } from 'react';
import { DataGridStoreApi } from '../store/useDataGridStore';
import './rsDataGridPager.scss';

export interface RsDataGridPagerProps {
  pagination: boolean;
  pagingSizes: number[];
  currentPagingSize: number;
  pageListSize: number;
  store: DataGridStoreApi;
}

export const RsDataGridPager = ({ pagination, pagingSizes, currentPagingSize, pageListSize, store }: RsDataGridPagerProps) => {
  const { pageSize, pageNumber, pageList, pageLimit, changePageListSize, changePageSize, changePageNumber, increasePageNum, decreasePageNum, lastPageNum } = store;

  const didInit = useRef(false);
  useEffect(() => {
    changePageListSize(pageListSize);
    changePageSize(currentPagingSize);
    didInit.current = true;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!didInit.current) {
      return;
    }
    changePageListSize(pageListSize);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pageListSize]);

  useEffect(() => {
    if (!didInit.current) {
      return;
    }
    changePageNumber(0);
    changePageSize(currentPagingSize);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentPagingSize]);

  const changeCurrentPaginationSize = (val: number) => {
    changePageNumber(0);
    changePageSize(val);
  };

  const setpage = (index: number) => changePageNumber(index);
  const increasePager = () => increasePageNum();
  const decreasePager = () => decreasePageNum();
  const lastPage = () => lastPageNum();

  const writeAS = (pageFirstItem: any, listSize: any, limit: any) => pageFirstItem + listSize > limit ? false : true;

  if (!pagination) {
    return null;
  }

  return (
    <div className="full-row row-layout-space-between-center">
      <div className="row-layout-start page-number-background">
        <div className="page-numbers" onClick={decreasePager}>{'<'}</div>
        {pageList.map(page => (
          <div
            key={page}
            className={'page-numbers' + (pageNumber === page - 1 ? ' page-numbers-selected' : '')}
            onClick={() => setpage(page - 1)}
          >
            {page}
          </div>
        ))}
        {writeAS(pageList?.[0], pageListSize, pageLimit) && (
          <div className="page-numbers" onClick={lastPage}>
            {pageLimit}
          </div>
        )}
        <div className="page-numbers" onClick={increasePager}>{'>'}</div>
      </div>
      <div className="row-layout">
        {pagingSizes.map(item => (
          <button
            key={item}
            type="button"
            className={'pager-size' + (item === pageSize ? ' page-selected' : '')}
            onClick={() => changeCurrentPaginationSize(item)}
          >
            {item}
          </button>
        ))}
      </div>
    </div>
  );
};

// rs-data-grid-vue/src/components/rsDataGrid/rsDataGridPager/RsDataGridPager.vue
<script setup lang="ts">
import { onMounted, watch } from 'vue';
import type { DataGridStoreApi } from '../store/useDataGridStore';

const props = defineProps<{
  pagination: boolean;
  pagingSizes: number[];
  currentPagingSize: number;
  pageListSize: number;
  store: DataGridStoreApi;
}>();

onMounted(() => {
  props.store.changePageListSize(props.pageListSize);
  props.store.changePageSize(props.currentPagingSize);
});

watch(
  () => props.pageListSize,
  value => props.store.changePageListSize(value)
);

watch(
  () => props.currentPagingSize,
  value => {
    props.store.changePageNumber(0);
    props.store.changePageSize(value);
  }
);

const changeCurrentPaginationSize = (val: number) => {
  props.store.changePageNumber(0);
  props.store.changePageSize(val);
};

const setpage = (index: number) => props.store.changePageNumber(index);
const increasePager = () => props.store.increasePageNum();
const decreasePager = () => props.store.decreasePageNum();
const lastPage = () => props.store.lastPageNum();

const writeAS = (pageFirstItem: any, pageListSize: any, pageLimit: any) => (pageFirstItem + pageListSize > pageLimit ? false : true);
</script>

<template>
  <div v-if="pagination" class="full-row row-layout-space-between-center pager-row">
    <div class="row-layout-start page-number-background">
      <div class="page-numbers" @click="decreasePager">{{ '<' }}</div>
      <div
        v-for="page in store.pageList"
        :key="page"
        class="page-numbers"
        :class="{ 'page-numbers-selected': store.pageNumber === page - 1 }"
        @click="setpage(page - 1)"
      >
        {{ page }}
      </div>
      <div v-if="writeAS(store.pageList?.[0], pageListSize, store.pageLimit)" class="page-numbers" @click="lastPage">
        {{ store.pageLimit }}
      </div>
      <div class="page-numbers" @click="increasePager">{{ '>' }}</div>
    </div>
    <div class="row-layout">
      <button
        v-for="item in pagingSizes"
        :key="item"
        type="button"
        class="pager-size"
        :class="{ 'page-selected': item === store.pageSize }"
        @click="changeCurrentPaginationSize(item)"
      >
        {{ item }}
      </button>
    </div>
  </div>
</template>

<style scoped src="./RsDataGridPager.scss"></style>
