// rs-data-grid-react/src/components/rsDataGrid/dialogs/ConfirmDialog.tsx
import { Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material';
import './dialogs.scss';

export interface ConfirmDialogProps {
  open: boolean;
  title?: string;
  message: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export const ConfirmDialog = ({ open, title, message, onConfirm, onCancel }: ConfirmDialogProps) => {
  return (
    <Dialog open={open} onClose={onCancel}>
      <DialogTitle>{title || 'Confirm'}</DialogTitle>
      <DialogContent>
        <p className="confirm-message">{message}</p>
      </DialogContent>
      <DialogActions>
        <Button onClick={onCancel}>No</Button>
        <Button variant="contained" color="error" onClick={onConfirm}>
          Yes
        </Button>
      </DialogActions>
    </Dialog>
  );
};

// rs-data-grid-vue/src/components/rsDataGrid/dialogs/ConfirmDialog.vue
<script setup lang="ts">
defineProps<{
  open: boolean;
  title?: string;
  message: string;
}>();

const emit = defineEmits<{
  confirm: [];
  cancel: [];
}>();
</script>

<template>
  <v-dialog :model-value="open" max-width="480" @update:model-value="value => !value && emit('cancel')">
    <v-card>
      <v-card-title>{{ title || 'Confirm' }}</v-card-title>
      <v-card-text>
        <p class="confirm-message">{{ message }}</p>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn variant="text" @click="emit('cancel')">No</v-btn>
        <v-btn variant="flat" color="error" @click="emit('confirm')">Yes</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped src="./dialogs.scss"></style>
