// rs-data-grid-react/src/components/rsDataGrid/dialogs/EditRowDialog.tsx
import { useEffect, useState } from 'react';
import { Dialog, DialogTitle, DialogContent, DialogActions, Button } from '@mui/material';
import { IColumn } from '../models/rsDataGrid.models';
import './dialogs.scss';

export interface EditRowDialogProps {
  open: boolean;
  row?: any;
  columns?: IColumn[];
  onSave: (result: Record<string, any>) => void;
  onCancel: () => void;
}

interface EditField {
  key: string;
}

export const EditRowDialog = ({ open, row, columns, onSave, onCancel }: EditRowDialogProps) => {
  const [fields, setFields] = useState<EditField[]>([]);
  const [editableRow, setEditableRow] = useState<Record<string, string>>({});

  useEffect(() => {
    if (!open) {
      return;
    }
    const nextFields: EditField[] = [];
    const nextEditable: Record<string, string> = {};
    if (row) {
      for (const [key, value] of Object.entries(row)) {
        nextFields.push({ key });
        nextEditable[key] = value === null || value === undefined ? '' : String(value);
      }
    } else {
      for (const column of columns ?? []) {
        nextFields.push({ key: column.dataField });
        nextEditable[column.dataField] = '';
      }
    }
    setFields(nextFields);
    setEditableRow(nextEditable);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, row, columns]);

  const handleSave = () => {
    const result: Record<string, any> = { ...row };
    for (const field of fields) {
      result[field.key] = editableRow[field.key];
    }
    onSave(result);
  };

  return (
    <Dialog open={open} onClose={onCancel}>
      <DialogTitle>{row ? 'Edit row' : 'Add row'}</DialogTitle>
      <DialogContent>
        <div className="edit-form">
          {fields.map(field => (
            <div className="edit-row" key={field.key}>
              <label className="edit-label">{field.key}</label>
              <input
                type="text"
                className="edit-input"
                value={editableRow[field.key] ?? ''}
                onChange={e => setEditableRow({ ...editableRow, [field.key]: e.target.value })}
              />
            </div>
          ))}
        </div>
      </DialogContent>
      <DialogActions>
        <Button onClick={onCancel}>Cancel</Button>
        <Button variant="contained" color="primary" onClick={handleSave}>
          Save
        </Button>
      </DialogActions>
    </Dialog>
  );
};

// rs-data-grid-vue/src/components/rsDataGrid/dialogs/EditRowDialog.vue
<script setup lang="ts">
import { reactive, ref, watch } from 'vue';
import type { IColumn } from '../models/rsDataGrid.models';

const props = defineProps<{
  open: boolean;
  row?: any;
  columns?: IColumn[];
}>();

const emit = defineEmits<{
  save: [result: Record<string, any>];
  cancel: [];
}>();

interface EditField {
  key: string;
}

const fields = ref<EditField[]>([]);
const editableRow = reactive<Record<string, string>>({});

watch(
  () => [props.open, props.row, props.columns] as const,
  () => {
    if (!props.open) {
      return;
    }
    const nextFields: EditField[] = [];
    Object.keys(editableRow).forEach(key => delete editableRow[key]);
    if (props.row) {
      for (const [key, value] of Object.entries(props.row)) {
        nextFields.push({ key });
        editableRow[key] = value === null || value === undefined ? '' : String(value);
      }
    } else {
      for (const column of props.columns ?? []) {
        nextFields.push({ key: column.dataField });
        editableRow[column.dataField] = '';
      }
    }
    fields.value = nextFields;
  },
  { immediate: true }
);

const handleSave = () => {
  const result: Record<string, any> = { ...props.row };
  for (const field of fields.value) {
    result[field.key] = editableRow[field.key];
  }
  emit('save', result);
};
</script>

<template>
  <v-dialog :model-value="open" max-width="480" @update:model-value="value => !value && emit('cancel')">
    <v-card>
      <v-card-title>{{ row ? 'Edit row' : 'Add row' }}</v-card-title>
      <v-card-text>
        <div class="edit-form">
          <div class="edit-row" v-for="field in fields" :key="field.key">
            <label class="edit-label">{{ field.key }}</label>
            <input type="text" class="edit-input" v-model="editableRow[field.key]" />
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn variant="text" @click="emit('cancel')">Cancel</v-btn>
        <v-btn variant="flat" color="primary" @click="handleSave">Save</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped src="./dialogs.scss"></style>
