// rs-data-grid-react/src/components/rsDataGrid/dialogs/GridSettingsDialog.tsx
import { useMemo, useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Chip,
  FormControl,
  InputLabel,
  Select,
  OutlinedInput,
  MenuItem,
  Checkbox,
  ListItemText,
  Typography,
  ThemeProvider,
  createTheme,
} from '@mui/material';
import type { SelectChangeEvent } from '@mui/material';
import { IColumn } from '../models/rsDataGrid.models';
import './dialogs.scss';

export interface GridSettingsDialogProps {
  open: boolean;
  columns: IColumn[];
  selected: string[];
  theme?: 'dark' | 'light';
  container?: Element | null;
  onChange: (next: string[]) => void;
  onClose: () => void;
}

export const GridSettingsDialog = ({ open, columns, selected, theme = 'light', container, onChange, onClose }: GridSettingsDialogProps) => {
  const muiTheme = useMemo(() => createTheme({ palette: { mode: theme } }), [theme]);
  const [draggedField, setDraggedField] = useState<string | null>(null);
  const [dragOverField, setDragOverField] = useState<string | null>(null);

  const byField = useMemo(() => new Map(columns.map(column => [column.dataField, column])), [columns]);
  const captionFor = (field: string): string => byField.get(field)?.caption ?? field;

  const handleSelectChange = (event: SelectChangeEvent<string[]>) => {
    const value = event.target.value;
    onChange(typeof value === 'string' ? value.split(',') : value);
  };

  const moveSelected = (fromField: string, toField: string) => {
    if (fromField === toField) {
      return;
    }
    const fromIndex = selected.indexOf(fromField);
    const toIndexOriginal = selected.indexOf(toField);
    if (fromIndex === -1 || toIndexOriginal === -1) {
      return;
    }
    const next = selected.slice();
    next.splice(fromIndex, 1);
    let insertAt = next.indexOf(toField);
    if (fromIndex < toIndexOriginal) {
      insertAt += 1;
    }
    next.splice(insertAt, 0, fromField);
    onChange(next);
  };

  return (
    <ThemeProvider theme={muiTheme}>
      <Dialog open={open} onClose={onClose} container={container} maxWidth="sm" fullWidth>
        <DialogTitle>Grid Settings</DialogTitle>
        <DialogContent>
          <div className="grid-settings-section">
            <Typography variant="caption" className="grid-settings-hint">
              Pick which columns to show. Nothing selected shows every column.
            </Typography>
            <FormControl fullWidth size="small">
              <InputLabel id="grid-settings-columns-label">Columns</InputLabel>
              <Select
                labelId="grid-settings-columns-label"
                multiple
                value={selected}
                onChange={handleSelectChange}
                input={<OutlinedInput label="Columns" />}
                renderValue={values => (
                  <div className="grid-settings-chip-row">
                    {values.map(field => (
                      <Chip key={field} label={captionFor(field)} size="small" />
                    ))}
                  </div>
                )}
              >
                {columns.map(column => (
                  <MenuItem key={column.dataField} value={column.dataField}>
                    <Checkbox checked={selected.includes(column.dataField)} size="small" />
                    <ListItemText primary={column.caption} />
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </div>
          {selected.length > 0 && (
            <div className="grid-settings-section">
              <Typography variant="subtitle2" className="grid-settings-heading">
                Visible order
              </Typography>
              <Typography variant="caption" className="grid-settings-hint">
                Drag to reorder.
              </Typography>
              <div className="grid-settings-chip-row">
                {selected.map(field => (
                  <Chip
                    key={field}
                    label={captionFor(field)}
                    color="primary"
                    onDelete={() => onChange(selected.filter(f => f !== field))}
                    className={'grid-settings-drag-chip' + (dragOverField === field ? ' grid-settings-drag-chip-over' : '')}
                    draggable
                    onDragStart={() => setDraggedField(field)}
                    onDragEnd={() => {
                      setDraggedField(null);
                      setDragOverField(null);
                    }}
                    onDragOver={event => {
                      event.preventDefault();
                      setDragOverField(field);
                    }}
                    onDragLeave={() => setDragOverField(current => (current === field ? null : current))}
                    onDrop={event => {
                      event.preventDefault();
                      if (draggedField) {
                        moveSelected(draggedField, field);
                      }
                      setDragOverField(null);
                      setDraggedField(null);
                    }}
                  />
                ))}
              </div>
            </div>
          )}
        </DialogContent>
        <DialogActions>
          {selected.length > 0 && (
            <Button onClick={() => onChange([])} color="inherit">
              Clear
            </Button>
          )}
          <Button variant="contained" onClick={onClose}>
            Close
          </Button>
        </DialogActions>
      </Dialog>
    </ThemeProvider>
  );
};

// rs-data-grid-vue/src/components/rsDataGrid/dialogs/GridSettingsDialog.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { IColumn } from '../models/rsDataGrid.models';

const props = defineProps<{
  open: boolean;
  columns: IColumn[];
  selected: string[];
  theme?: 'dark' | 'light';
}>();

const emit = defineEmits<{
  'update:selected': [next: string[]];
  close: [];
}>();

const draggedField = ref<string | null>(null);
const dragOverField = ref<string | null>(null);

const captionFor = (field: string): string => props.columns.find(column => column.dataField === field)?.caption ?? field;

const onSelectChange = (value: string[]) => {
  emit('update:selected', value);
};

const removeColumn = (dataField: string) => {
  emit('update:selected', props.selected.filter(field => field !== dataField));
};

const moveSelected = (fromField: string, toField: string) => {
  if (fromField === toField) {
    return;
  }
  const fromIndex = props.selected.indexOf(fromField);
  const toIndexOriginal = props.selected.indexOf(toField);
  if (fromIndex === -1 || toIndexOriginal === -1) {
    return;
  }
  const next = props.selected.slice();
  next.splice(fromIndex, 1);
  let insertAt = next.indexOf(toField);
  if (fromIndex < toIndexOriginal) {
    insertAt += 1;
  }
  next.splice(insertAt, 0, fromField);
  emit('update:selected', next);
};
</script>

<template>
  <v-dialog :model-value="open" max-width="480" @update:model-value="value => !value && emit('close')">
    <v-card :data-rg-theme="theme ?? 'light'">
      <v-card-title>Grid Settings</v-card-title>
      <v-card-text>
        <div class="grid-settings-section">
          <div class="grid-settings-hint">Pick which columns to show. Nothing selected shows every column.</div>
          <v-select
            :model-value="selected"
            @update:model-value="onSelectChange"
            :items="columns"
            item-title="caption"
            item-value="dataField"
            label="Columns"
            variant="outlined"
            density="compact"
            multiple
            chips
            closable-chips
          ></v-select>
        </div>
        <div v-if="selected.length > 0" class="grid-settings-section">
          <div class="grid-settings-heading">Visible order</div>
          <div class="grid-settings-hint">Drag to reorder.</div>
          <div class="grid-settings-chip-row">
            <v-chip
              v-for="field in selected"
              :key="field"
              color="primary"
              variant="flat"
              closable
              class="grid-settings-drag-chip"
              :class="{ 'grid-settings-drag-chip-over': dragOverField === field }"
              :draggable="true"
              @click:close="removeColumn(field)"
              @dragstart="draggedField = field"
              @dragend="() => { draggedField = null; dragOverField = null; }"
              @dragover.prevent="dragOverField = field"
              @dragleave="dragOverField = dragOverField === field ? null : dragOverField"
              @drop.prevent="() => { if (draggedField) moveSelected(draggedField, field); dragOverField = null; draggedField = null; }"
            >
              {{ captionFor(field) }}
            </v-chip>
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn v-if="selected.length > 0" variant="text" @click="emit('update:selected', [])">Clear</v-btn>
        <v-btn variant="flat" color="primary" @click="emit('close')">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped src="./dialogs.scss"></style>
