// rs-data-grid-angular/src/app/rsivri-grid/dialogs/grid-settings-dialog.component.ts
import { Component, EventEmitter, Output, inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';
import { MatChipsModule } from '@angular/material/chips';
import { IColumn } from '../../../core/models/IColumn';

export interface GridSettingsDialogData {
  columns: IColumn[];
  selected: string[];
}

@Component({
  selector: 'rsivri-grid-settings-dialog',
  standalone: true,
  imports: [MatDialogModule, MatButtonModule, MatSelectModule, MatChipsModule],
  templateUrl: './grid-settings-dialog.component.html',
  styleUrls: ['./grid-settings-dialog.component.css']
})
export class GridSettingsDialogComponent {
  private readonly dialogRef = inject(MatDialogRef<GridSettingsDialogComponent>);
  readonly data = inject<GridSettingsDialogData>(MAT_DIALOG_DATA);

  @Output() selectedChange = new EventEmitter<string[]>();

  selected: string[] = [...this.data.selected];
  draggedField: string | null = null;
  dragOverField: string | null = null;

  captionFor(field: string): string {
    return this.data.columns.find(column => column.dataField === field)?.caption ?? field;
  }

  onSelectChange(value: string[]): void {
    this.selected = value;
    this.selectedChange.emit(this.selected);
  }

  removeColumn(field: string): void {
    this.selected = this.selected.filter(f => f !== field);
    this.selectedChange.emit(this.selected);
  }

  clearAll(): void {
    this.selected = [];
    this.selectedChange.emit(this.selected);
  }

  onDragStart(field: string, event: DragEvent): void {
    this.draggedField = field;
    if (event.dataTransfer) {
      event.dataTransfer.effectAllowed = 'move';
    }
  }

  onDragEnd(): void {
    this.draggedField = null;
    this.dragOverField = null;
  }

  onDragOver(field: string, event: DragEvent): void {
    event.preventDefault();
    this.dragOverField = field;
  }

  onDragLeave(field: string): void {
    if (this.dragOverField === field) {
      this.dragOverField = null;
    }
  }

  onDrop(field: string, event: DragEvent): void {
    event.preventDefault();
    if (this.draggedField) {
      this.moveSelected(this.draggedField, field);
    }
    this.dragOverField = null;
    this.draggedField = null;
  }

  private moveSelected(fromField: string, toField: string): void {
    if (fromField === toField) {
      return;
    }
    const fromIndex = this.selected.indexOf(fromField);
    const toIndexOriginal = this.selected.indexOf(toField);
    if (fromIndex === -1 || toIndexOriginal === -1) {
      return;
    }
    const next = this.selected.slice();
    next.splice(fromIndex, 1);
    let insertAt = next.indexOf(toField);
    if (fromIndex < toIndexOriginal) {
      insertAt += 1;
    }
    next.splice(insertAt, 0, fromField);
    this.selected = next;
    this.selectedChange.emit(this.selected);
  }

  onClose(): void {
    this.dialogRef.close();
  }
}

<h2 mat-dialog-title>Grid Settings</h2>
<mat-dialog-content>
  <div class="grid-settings-section">
    <div class="grid-settings-hint">Pick which columns to show. Nothing selected shows every column.</div>
    <mat-form-field appearance="outline" class="grid-settings-select">
      <mat-label>Columns</mat-label>
      <mat-select multiple [value]="selected" (selectionChange)="onSelectChange($event.value)">
        <mat-select-trigger>
          <div class="grid-settings-chip-row">
            @for (field of selected; track field) {
              <span class="grid-settings-trigger-chip">{{ captionFor(field) }}</span>
            }
          </div>
        </mat-select-trigger>
        @for (column of data.columns; track column.dataField) {
          <mat-option [value]="column.dataField">{{ column.caption }}</mat-option>
        }
      </mat-select>
    </mat-form-field>
  </div>
  @if (selected.length > 0) {
    <div class="grid-settings-section">
      <div class="grid-settings-heading">Visible order</div>
      <div class="grid-settings-hint">Drag to reorder.</div>
      <mat-chip-set class="grid-settings-chip-row">
        @for (field of selected; track field) {
          <mat-chip
            class="grid-settings-drag-chip"
            [class.grid-settings-drag-chip-over]="dragOverField === field"
            [draggable]="true"
            (dragstart)="onDragStart(field, $event)"
            (dragend)="onDragEnd()"
            (dragover)="onDragOver(field, $event)"
            (dragleave)="onDragLeave(field)"
            (drop)="onDrop(field, $event)"
          >
            {{ captionFor(field) }}
            <button type="button" class="grid-settings-chip-remove" aria-label="Remove" (click)="removeColumn(field)">&times;</button>
          </mat-chip>
        }
      </mat-chip-set>
    </div>
  }
</mat-dialog-content>
<mat-dialog-actions align="end">
  @if (selected.length > 0) {
    <button mat-button type="button" (click)="clearAll()">Clear</button>
  }
  <button mat-raised-button color="primary" type="button" (click)="onClose()">Close</button>
</mat-dialog-actions>

// rs-data-grid-vue/src/components/rsDataGrid/dialogs/GridSettingsDialog.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { IColumn } from '../models/rsDataGrid.models';

const props = defineProps<{
  open: boolean;
  columns: IColumn[];
  selected: string[];
  theme?: 'dark' | 'light';
}>();

const emit = defineEmits<{
  'update:selected': [next: string[]];
  close: [];
}>();

const draggedField = ref<string | null>(null);
const dragOverField = ref<string | null>(null);

const captionFor = (field: string): string => props.columns.find(column => column.dataField === field)?.caption ?? field;

const onSelectChange = (value: string[]) => {
  emit('update:selected', value);
};

const removeColumn = (dataField: string) => {
  emit('update:selected', props.selected.filter(field => field !== dataField));
};

const moveSelected = (fromField: string, toField: string) => {
  if (fromField === toField) {
    return;
  }
  const fromIndex = props.selected.indexOf(fromField);
  const toIndexOriginal = props.selected.indexOf(toField);
  if (fromIndex === -1 || toIndexOriginal === -1) {
    return;
  }
  const next = props.selected.slice();
  next.splice(fromIndex, 1);
  let insertAt = next.indexOf(toField);
  if (fromIndex < toIndexOriginal) {
    insertAt += 1;
  }
  next.splice(insertAt, 0, fromField);
  emit('update:selected', next);
};
</script>

<template>
  <v-dialog :model-value="open" max-width="480" @update:model-value="value => !value && emit('close')">
    <v-card :data-rg-theme="theme ?? 'light'">
      <v-card-title>Grid Settings</v-card-title>
      <v-card-text>
        <div class="grid-settings-section">
          <div class="grid-settings-hint">Pick which columns to show. Nothing selected shows every column.</div>
          <v-select
            :model-value="selected"
            @update:model-value="onSelectChange"
            :items="columns"
            item-title="caption"
            item-value="dataField"
            label="Columns"
            variant="outlined"
            density="compact"
            multiple
            chips
            closable-chips
          ></v-select>
        </div>
        <div v-if="selected.length > 0" class="grid-settings-section">
          <div class="grid-settings-heading">Visible order</div>
          <div class="grid-settings-hint">Drag to reorder.</div>
          <div class="grid-settings-chip-row">
            <v-chip
              v-for="field in selected"
              :key="field"
              color="primary"
              variant="flat"
              closable
              class="grid-settings-drag-chip"
              :class="{ 'grid-settings-drag-chip-over': dragOverField === field }"
              :draggable="true"
              @click:close="removeColumn(field)"
              @dragstart="draggedField = field"
              @dragend="() => { draggedField = null; dragOverField = null; }"
              @dragover.prevent="dragOverField = field"
              @dragleave="dragOverField = dragOverField === field ? null : dragOverField"
              @drop.prevent="() => { if (draggedField) moveSelected(draggedField, field); dragOverField = null; draggedField = null; }"
            >
              {{ captionFor(field) }}
            </v-chip>
          </div>
        </div>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn v-if="selected.length > 0" variant="text" @click="emit('update:selected', [])">Clear</v-btn>
        <v-btn variant="flat" color="primary" @click="emit('close')">Close</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style scoped src="./dialogs.scss"></style>
